sudo: false

language: java
jdk: oraclejdk8

# publish snapshots to https://oss.jfrog.org/libs-snapshot/org/ethereum/ethereumj-core
# publish releases to http://jcenter.bintray.com/org/ethereum/ethereumj-core
# publish coverage to https://coveralls.io/r/ethereum/ethereumj
script:
  - ./gradlew clean build publish jacocoTestReport coveralls --stacktrace


cache:
  directories:
    - $HOME/.gradle

notifications:
  irc:
    channels: chat.freenode.net#ethereumj
    template:
      - '%{message} (%{repository}#%{build_number}, %{duration})'
      - '%{repository}/%{branch} %{commit} %{author}: %{commit_message}'
      - '%{build_url}'
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: "Fhaoka5w5XzIZS7ObKfVrnHaVLz7x2Owo1ygb+hXWAHiXpc3Oi1Q6yDOfye/z+Y0Gw8an8v23PIxhLoVZ6JpdurwCXo66dK2TkiNzmEWd6RtYPSZDm6f+0NjPBSOnP5rHmej7RvHeyTY/PQrGPtrHZZQTYD3AuRP1S+tGvtqikA="
  webhooks:
    on_success: change
    on_failure: always
    urls:
      - secure: "Ir1slcCUTWEbV5e39JPGIKYYnjvszD9L7/27TUkqDxiOl6iA4BY6vvg/e0dyZHR6VwbqEedGeEbxpkifZAJ5W/PE88jFa1PHuDHuEy309hWt+u1n2wY1jANnW/VPHO7v/p7oSeMa91cmRUJaIp5TB6hBW0i4CZxTGmwowFnu9y0="


# Encrypted values are ORG_GRADLE_PROJECT_bintrayUser and ORG_GRADLE_PROJECT_bintrayKey props for use by Travis when
# authenticating against oss.jfrog.org and/or Bintray repositories. See http://docs.travis-ci.com/user/encryption-keys
# http://www.gradle.org/docs/current/userguide/tutorial_this_and_that.html#sec:gradle_properties_and_system_properties
env:
  global:
    - JAVA_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    - secure: "BSdfBQsJi5VFcIF7Z50ddfjex60OZpd8OM7AxN+h93wxzBx/GD2bsWA9elwvrLFImByw5RIqE9xRvL4CioKZLgFiJCSFuPkf6I+6R6PsUhqklPvAJSXHlQXOM6bJD23rZewyfudh5JtqADVavY7vlXnmYXFeWKh8XdPYtRPlJV0="
    - secure: "iZcZikUHrdaxsc5at1KT0M/6D4OHdU2WTd/aFIBKERXteGw+okq+s+VWghnELEq3YsKfYRJrkslcA6Mpcxq7KrUMsSSX1kZ1ifsk2151sU3+fJpIYQ9pCeWboLWSF//A7IdEe+zHpRVFuHVGU05OAalNCmJ52TEe3/M0YkY5+e8="
